name: "Browser Plugin Publisher"
description: "Publish your browser plugin anywhere using a single action."
author: "Plasmo Corp."
inputs:
  keys: # change this
    required: true
    description: "A JSON string containing the keys to be used for the submission process."

runs:
  using: "node16"
  main: "dist/index.js"
