name: "Browser Platform Publisher"
description: "Publish your browser extension anywhere using a single action."
author: "Plasmo Corp."
branding:
  icon: upload-cloud
  color: purple
inputs:
  keys:
    required: true
    description: "A JSON string containing the keys to be used for the submission process. (This should be a secret)"
  artifact:
    required: false
    description: "The extension zip artifact to be published."
  zip:
    required: false
    description: "This is an alias to artifact argument."
  file:
    required: false
    description: "This is an alias to artifact argument."
  chrome-file:
    required: false
    description: "The path to the Chrome extension zip file."
  firefox-file:
    required: false
    description: "The path to the Firefox extension zip file."
  edge-file:
    required: false
    description: "The path to the Edge extension zip file."
  opera-file:
    required: false
    description: "The path to the Opera extension zip file."
  notes:
    required: false
    description: "A release note cataloging changes. (Edge only)"
  edge-notes:
    required: false
    description: "This is an alias to notes argument."
  verbose:
    required: false
    description: "Print out more verbose logging."
  version-file:
    required: false
    description: "The path to a json file with a version field, default to package.json."
runs:
  using: "node16"
  main: "index.js"
