name: PR testing
# rebuild any PRs and main branch changes
on:
  pull_request:
    branches:
      - main

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.2
          run_install: true
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3.1.0
        with:
          node-version: 16.x
          cache: "pnpm"
      - run: pnpm run all
